language: android
dist: trusty
before_install:
  - wget http://services.gradle.org/distributions/gradle-5.3-bin.zip
  - unzip -qq gradle-5.3-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.3
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
android:
  components:
    - build-tools-28.0.3
    - android-28
      #    - android-17
      #    - sys-img-x86-android-28
      #    - sys-img-armeabi-v7a-android-17
#before_script:
#  - echo no | android create avd --force -n test -t android-28 -c 100M
#  - emulator -avd test -no-audio -no-window &
#  - android-wait-for-emulator
script:
  - gradle build check
